[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
espflash = { version = "2.1", default-features = false }
serialport = { version = "4.6.0", default-features = false }
miette = "7.2.0"
log = "0.4.22"
