[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
espflash = { version = "3.2.0", features = ["serialport"] }
serialport = { version = "4.6.0", default-features = false }
miette = "7.2.0"
indicatif = { version = "0.17.8" }
log = "0.4.22"
esp-idf-part = "0.5.0"
